"""1.3.4

Revision ID: 7480d259772e
Revises: c8ebf2f4340e
Create Date: 2024-07-19 22:26:15.089515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7480d259772e'
down_revision = 'c8ebf2f4340e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SITE_BRUSH_TASK', sa.Column('BRUSHTASK_FREE_DDL_DELETE', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_BRUSH_TASK', 'BRUSHTASK_FREE_DDL_DELETE')
    # ### end Alembic commands ###
