"""1.3.4

Revision ID: 7480d259772e
Revises: c8ebf2f4340e
Create Date: 2024-07-19 22:26:15.089515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7480d259772e'
down_revision = 'c8ebf2f4340e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('BRUSHTASK_FREE_DDL_DELETE', sa.Text, nullable=True))
    except Exception as e:
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_BRUSH_TASK', 'BRUSHTASK_FREE_DDL_DELETE')
    # ### end Alembic commands ###
