"""1.3.3

Revision ID: c8ebf2f4340e
Revises: 57c4146172c2
Create Date: 2024-04-05 18:16:51.866389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ebf2f4340e'
down_revision = '57c4146172c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_SITE") as batch_op:
            batch_op.add_column(sa.Column('APIKEY', sa.Text, nullable=True))
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONFIG_SITE', 'APIKEY')
    # ### end Alembic commands ###
