"""1.3.5

Revision ID: d116d793ba9f
Revises: 7480d259772e
Create Date: 2024-10-13 11:27:54.003444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd116d793ba9f'
down_revision = '7480d259772e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_USER_INFO_STATS") as batch_op:
            batch_op.add_column(sa.Column('LAST_SEEN', sa.Text, nullable=True))
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_USER_INFO_STATS', 'LAST_SEEN')
    # ### end Alembic commands ###
